services:
  nats:
    image: nats:latest
    container_name: doris-nats
    command: "-js -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - queue_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8222/healthz" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - NATS_DISABLE_PING_ARRAY_CLIENT=true
      - NATS_NO_AUTH_USER=true
      - NATS_JETSTREAM=true
networks:
  queue_network:
    driver: bridge
