services:  
  postgres:
    image: ankane/pgvector:latest
    container_name: doris-codex-postgres
    ports:
      - "${DATABASE_PORT:-5433}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-doris-codex}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - local-network
  ollama:
    image: ollama/ollama
    container_name: doris-codex-ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=nomic-embed-text
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
